import {describe,it,expect,vi} from 'vitest';
import {callProvider,providerFor,readProviderStream} from '../server/providers';
describe('Provider compatibility',()=>{
 it('assembles a streamed Claude response including citations and stop reason',async()=>{const events=[{type:'message_start',message:{content:[]}},{type:'content_block_start',index:0,content_block:{type:'text',text:''}},{type:'content_block_delta',index:0,delta:{type:'text_delta',text:'Verified finding'}},{type:'content_block_delta',index:0,delta:{type:'citations_delta',citation:{url:'https://example.com',title:'Source'}}},{type:'message_delta',delta:{stop_reason:'end_turn'}},{type:'message_stop'}];const response=new Response(events.map(e=>'data: '+JSON.stringify(e)+'\n\n').join(''),{headers:{'Content-Type':'text/event-stream'}});const result=await readProviderStream(response,true);expect(result.content[0].text).toBe('Verified finding');expect(result.content[0].citations[0].url).toBe('https://example.com');expect(result.stop_reason).toBe('end_turn')});
 it('rejects a stream ending before the completion event',async()=>{await expect(readProviderStream(new Response('data: {"type":"message_start","message":{"content":[]}}\n\n'),true)).rejects.toThrow('interrupted')});
 it('selects the issuer of the key, including a previously saved OpenAI default model',()=>{expect(providerFor('sk-ant-test','gpt-5-mini')).toEqual({provider:'Anthropic',model:'claude-sonnet-4-6'});expect(providerFor('sk-proj-test','gpt-5-mini').provider).toBe('OpenAI')});
 it('sends an Anthropic key only to Anthropic and retains source citations',async()=>{const mock=vi.fn().mockResolvedValue(new Response(JSON.stringify({stop_reason:'end_turn',content:[{type:'web_search_tool_result',content:[{url:'https://example.com/report',title:'Report'}]},{type:'text',text:'A supported observation',citations:[{url:'https://example.com/report',title:'Report',cited_text:'Evidence'}]}]})));const r=await callProvider({max_output_tokens:1000,instructions:'Research',input:'Example',tools:[{type:'web_search'}]},'sk-ant-test','gpt-5-mini',new AbortController().signal,mock);expect(mock.mock.calls[0][0]).toBe('https://api.anthropic.com/v1/messages');expect(mock.mock.calls[0][1].headers).not.toHaveProperty('Authorization');expect(JSON.parse(mock.mock.calls[0][1].body).tools[0].name).toBe('web_search');expect(r.output[0].action.sources[0].url).toBe('https://example.com/report');expect(r.status).toBe('completed')});
 it('uses Claude structured output without unsupported length constraints',async()=>{const mock=vi.fn().mockResolvedValue(new Response(JSON.stringify({stop_reason:'end_turn',content:[{type:'text',text:'{"value":"valid"}'}]})));await callProvider({max_output_tokens:1000,instructions:'Extract',input:'Data',text:{format:{schema:{type:'object',properties:{value:{type:'string',minLength:1,maxLength:100}},required:['value'],additionalProperties:false}}}},'sk-ant-test','gpt-5-mini',new AbortController().signal,mock);const b=JSON.parse(mock.mock.calls[0][1].body);expect(b.output_config.format.schema.properties.value).toEqual({type:'string'});expect(b.tools).toBeUndefined()});
 it('continues paused server-tool turns without changing the assistant content',async()=>{const blocks=[{type:'text',text:'Checking sources'},{type:'server_tool_use',id:'tool1',name:'web_search',input:{query:'company'}}];const mock=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({stop_reason:'pause_turn',content:blocks}))).mockResolvedValueOnce(new Response(JSON.stringify({stop_reason:'end_turn',content:[{type:'text',text:'Finished'}]})));const r=await callProvider({max_output_tokens:1000,instructions:'Research',input:'Company',tools:[{}]},'sk-ant-test','gpt-5-mini',new AbortController().signal,mock);expect(JSON.parse(mock.mock.calls[1][1].body).messages[1].content).toEqual(blocks);expect(r.status).toBe('completed')});
});
