// @vitest-environment jsdom
import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
import {render,screen,cleanup,fireEvent,waitFor,act} from '@testing-library/react';
import '@testing-library/jest-dom/vitest';
import App from '../src/App';
import {targetDemo} from '../src/data/demo';
import {CompanyPath,CompanyResearch} from '../src/components/CompanyResearch';
// Canvas geometry cannot be checked in jsdom. These tests cover actual application flows.
vi.mock('../src/components/Graph',()=>({OverviewGraph:()=> <div>General graph canvas</div>,PathGraph:()=> <div>Path graph canvas</div>,CompanyOverviewGraph:()=> <div>Company graph canvas</div>}));
beforeEach(()=>{localStorage.clear();location.hash='map';vi.stubGlobal('matchMedia',()=>({matches:false,addEventListener:()=>{},removeEventListener:()=>{}}));vi.stubGlobal('scrollTo',()=>{});vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>({configured:false,model:'gpt-5-mini',token:'test'})}));});
afterEach(()=>{cleanup();vi.unstubAllGlobals();vi.useRealTimers()});
describe('Rep workflows',()=>{
 it('submits the typed company and applies the validated saved result',async()=>{const onActive=vi.fn();const mock=vi.fn(async(url:string)=>({ok:true,json:async()=>url==='/api/status'?{configured:true,model:'gpt-5-mini',token:'local-token'}:url==='/api/reports'?[]:url==='/api/research'?{id:'job-1'}:{status:'complete',phase:'Ready',report:targetDemo}}));vi.stubGlobal('fetch',mock);render(<CompanyResearch active={null} onActive={onActive} go={()=>{}} startDemo={()=>{}}/>);await waitFor(()=>expect(screen.getByRole('button',{name:'Research company'})).toBeDisabled());fireEvent.change(screen.getByLabelText('Company name or website'),{target:{value:'target.com'}});await waitFor(()=>expect(screen.getByRole('button',{name:'Research company'})).toBeEnabled());fireEvent.click(screen.getByRole('button',{name:'Research company'}));await waitFor(()=>expect(onActive).toHaveBeenCalledWith(targetDemo));const call=(mock.mock.calls as unknown as [string,RequestInit][]).find(c=>c[0]==='/api/research')!;expect(JSON.parse(call[1].body as string)).toEqual({query:'target.com'});expect(call[1].headers).not.toHaveProperty('Authorization');});
 it('shows one-time setup and does not submit without a key',async()=>{vi.stubGlobal('fetch',vi.fn(async(url:string)=>({ok:true,json:async()=>url==='/api/reports'?[]:{configured:false,model:'gpt-5-mini',token:'token'}})));render(<CompanyResearch active={null} onActive={()=>{}} go={()=>{}} startDemo={()=>{}}/>);await screen.findByText('One-time setup, then you’re ready.');fireEvent.change(screen.getByLabelText('Company name or website'),{target:{value:'Target'}});expect(screen.getByRole('button',{name:'Research company'})).toBeDisabled();});
 it('starts a fixed demo without calling the research API and opens one step at a time',async()=>{render(<App/>);fireEvent.click(screen.getByRole('button',{name:'Play demo'}));await screen.findByText('What the sources actually say');expect(screen.queryByText('Open with curiosity')).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Pause demo'}));fireEvent.click(screen.getByRole('button',{name:'4. People'}));expect(screen.getByText(targetDemo.paths[0].personaRationale)).toBeInTheDocument();expect(fetch).not.toHaveBeenCalled();});
 it('keeps research-backed call notes separate from the general guide',async()=>{localStorage.setItem('signalgraph-active-research',JSON.stringify(targetDemo));location.hash='play/fulfillment';render(<App/>);fireEvent.click(screen.getByRole('button',{name:/Call view/}));const notes=screen.getByLabelText('Call notes');fireEvent.change(notes,{target:{value:'Confirm order exception owner'}});const saved=JSON.parse(localStorage.getItem('signalgraph.workspace')!);expect(saved.saved[0].companyId).toBe('company:Target');expect(saved.saved[0].note).toContain('exception');expect(screen.getByText(targetDemo.paths[0].opener,{exact:false})).toBeInTheDocument();});
 it('lets a rep switch call types and inspect generic context',async()=>{location.hash='play/service';render(<App/>);fireEvent.click(screen.getByRole('button',{name:/Call view/}));fireEvent.click(screen.getByRole('button',{name:'Follow-up'}));expect(screen.getByText(/Use your actual notes/)).toBeInTheDocument();fireEvent.click(screen.getAllByRole('button',{name:'What could make this wrong?'})[0]);expect(screen.getByRole('dialog')).toBeInTheDocument();fireEvent.keyDown(document,{key:'Escape'});expect(screen.queryByRole('dialog')).not.toBeInTheDocument();});
 it('keeps Comparison in a separate tab and does not falsely mark unknown features absent',async()=>{location.hash='comparison';render(<App/>);expect(screen.getByRole('table')).toBeInTheDocument();expect(screen.getAllByText('Not verified').length).toBeGreaterThan(0);expect(screen.getByText('A promising learning advantage—not a proven win.')).toBeInTheDocument();});
 it('can focus the main map and exit with Escape',()=>{const {container}=render(<App/>);fireEvent.click(screen.getByRole('button',{name:'Full-screen map'}));expect(container.querySelector('.map-focus')).toBeInTheDocument();fireEvent.keyDown(window,{key:'Escape'});expect(container.querySelector('.map-focus')).not.toBeInTheDocument();});
 it('automatically advances the demo only while playing',()=>{vi.useFakeTimers();const props={report:targetDemo,path:targetDemo.paths[0],go:vi.fn(),onPlaying:vi.fn()};const view=render(<CompanyPath {...props} playing={false}/>);vi.advanceTimersByTime(30000);expect(screen.getByText('What the sources actually say')).toBeInTheDocument();view.rerender(<CompanyPath {...props} playing/>);act(()=>{vi.advanceTimersByTime(27000)});expect(screen.getByText('A reason to ask—not proof of urgency')).toBeInTheDocument();});
});
