import {useEffect,useRef,useState} from 'react';
import {Search,ArrowRight,ArrowLeft,ExternalLink,Building2,FileText,CheckCircle2,TriangleAlert,Loader2,Download,Trash2,X,Compass,Pause,Play} from 'lucide-react';
import {reportSchema,type ResearchReport,type ResearchPath} from '../domain/research';
import {playById} from '../data/plays';
import {personaById} from '../data/personas';
import {productById} from '../data/catalog';
import {download} from '../services/storage';

export function loadActiveResearch():ResearchReport|null{try{return reportSchema.parse(JSON.parse(localStorage.getItem('signalgraph-active-research')||'null'))}catch{return null}}
async function api(path:string,body?:unknown){
 let token='';if(body!==undefined){const status=await fetch('/api/status').then(r=>r.json());token=status.token}
 const r=await fetch(path,body===undefined?undefined:{method:'POST',headers:{'Content-Type':'application/json','X-SignalGraph-Token':token},body:JSON.stringify(body)});
 const data=await r.json();if(!r.ok)throw Error(data.error||'Request failed.');return data;
}
function Sources({report,ids}:{report:ResearchReport;ids:string[]}){return <div className="research-citations">{report.sources.filter(s=>ids.includes(s.id)).map(s=><a key={s.id} href={s.url} target="_blank" rel="noreferrer">{s.id} · {s.title}<ExternalLink size={12}/></a>)}</div>}
export function CompanyResearch({active,onActive,go,startDemo}:{startDemo:()=>void;active:ResearchReport|null;onActive:(r:ResearchReport|null)=>void;go:(r:string)=>void}){
 const [status,setStatus]=useState<{configured:boolean;model:string;provider?:string}|null>(null),[reports,setReports]=useState<ResearchReport[]>([]),[query,setQuery]=useState(''),[error,setError]=useState(''),[phase,setPhase]=useState(''),[job,setJob]=useState(()=>{try{return localStorage.getItem('signalgraph-research-job')||''}catch{return ''}}),[submitting,setSubmitting]=useState(false);
 const activeCallback=useRef(onActive);activeCallback.current=onActive;
 const refresh=async()=>{try{setStatus(await api('/api/status'));const result=await api('/api/reports');setReports(result.map((r:unknown)=>reportSchema.parse(r)))}catch{setError('Open SignalForce using SignalForce.app on your Desktop to connect the local research service. The general map still works offline.')}};
 useEffect(()=>{void refresh()},[]);
 useEffect(()=>{
  if(!job)return;let disposed=false,timer:ReturnType<typeof setTimeout>;
  const poll=async()=>{try{const result=await api(`/api/jobs/${job}`);if(disposed)return;setPhase(result.phase);if(result.status==='complete'){const report=reportSchema.parse(result.report);activeCallback.current(report);setReports(old=>[report,...old.filter(x=>x.id!==report.id)]);finish();}else if(result.status==='failed'||result.status==='cancelled'){setError(result.error||'Research did not complete.');finish()}else timer=setTimeout(poll,1800)}catch(e){if(!disposed){setError(e instanceof Error?e.message:'Connection interrupted.');finish()}}};
  const finish=()=>{setJob('');try{localStorage.removeItem('signalgraph-research-job')}catch{}};
  void poll();return()=>{disposed=true;clearTimeout(timer)};
 },[job]);
 const start=async()=>{if(!query.trim()||job||submitting)return;setError('');setSubmitting(true);try{const result=await api('/api/research',{query:query.trim()});setJob(result.id);setPhase('Starting research');try{localStorage.setItem('signalgraph-research-job',result.id)}catch{}}catch(e){setError(e instanceof Error?e.message:'Could not start research.')}finally{setSubmitting(false)}};
 const remove=async(id:string)=>{try{await api('/api/delete',{id});setReports(old=>old.filter(r=>r.id!==id));if(active?.id===id)onActive(null)}catch(e){setError(e instanceof Error?e.message:'Could not delete report.')}};
 return <><div className="page-heading"><div><div className="eyebrow">COMPANY LENS</div><h1>Make the map specific.</h1><p>Research the business. Follow the evidence. Find a useful conversation.</p></div><button className="button secondary" onClick={startDemo}><Compass size={16}/>Try the Target demo · no API</button></div>
 <section className="research-search-card"><div className="research-search-icon"><Search size={27}/></div><div><h2>Who are you speaking with?</h2><p>Enter a company name or its website. A website helps distinguish similar names.</p><form onSubmit={e=>{e.preventDefault();void start()}}><input aria-label="Company name or website" placeholder="e.g. a company name or company.com" value={query} onChange={e=>setQuery(e.target.value)} maxLength={200}/><button className="button primary" disabled={!status?.configured||!!job||submitting||query.trim().length<2}>{job||submitting?<Loader2 size={17}/>:<Search size={17}/>}Research company</button></form><p className="caption">Uses your {status?.provider||'AI provider'} API project · API usage is billed separately · Reports are saved on this Mac.</p></div></section>
 {status&&!status.configured&&<div className="research-setup"><FileText size={24}/><div><h3>One-time setup, then you’re ready.</h3><p>Double-click <strong>Set Up SignalForce Research.command</strong> on your Desktop. Paste an OpenAI or Anthropic API key in Terminal; typing stays hidden. It is stored outside the browser in a file only your Mac user can read.</p><button className="button secondary" onClick={()=>{setError('');void refresh()}}>I’ve saved my key — check connection</button></div></div>}
 {error&&<div className="error" role="alert">{error}<button className="icon-button" aria-label="Dismiss research error" onClick={()=>setError('')}><X size={15}/></button></div>}
 {job&&<div className="research-progress" role="status"><Loader2 className="research-spinner" size={22}/><div><strong>{phase||'Reconnecting to research'}</strong><p>Checking public sources and their limits. This can take several minutes; there is no need to keep clicking.</p></div><button className="button secondary" onClick={async()=>{try{await api('/api/cancel',{id:job})}catch{setError('Could not cancel. Check the local server connection.')}}}>Cancel</button></div>}
 <div className="research-layout"><div>{active?<Report report={active} go={go}/>:<div className="research-empty"><Compass size={40}/><h2>A company-specific route through the map.</h2><p>Sources become findings. Findings suggest paths. Each path gives you an owner, a solution approach, and questions that test the idea.</p><div className="research-flow"><span>Published evidence</span><ArrowRight size={17}/><span>Possible problem</span><ArrowRight size={17}/><span>Better questions</span></div><p className="caption">No invented buying scores. No assumption that every company needs a Salesforce product.</p></div>}</div><aside className="research-history content-card"><h3>Saved research</h3><p className="caption">Select a report to apply its company lens. Refresh by running a new search.</p>{reports.length?reports.map(r=><div key={r.id} className={`research-history-row ${active?.id===r.id?'active':''}`}><button onClick={()=>onActive(r)}><Building2 size={17}/><span><strong>{r.company.name}</strong><small>{new Date(r.createdAt).toLocaleDateString()} · {r.paths.length} paths</small></span></button><button className="icon-button" aria-label={`Delete research for ${r.company.name}`} onClick={()=>void remove(r.id)}><Trash2 size={15}/></button></div>):<p className="caption">Your first report will appear here.</p>}{active&&<button className="text-link" onClick={()=>onActive(null)}>Remove company lens <X size={14}/></button>}<div className="research-coverage-key"><strong>What research looks for</strong><p>Filings · Earnings · Hiring · Strategy · Leadership · Operations · Customer experience · Financial constraints</p></div></aside></div></>;
}
function Report({report:r,go}:{report:ResearchReport;go:(r:string)=>void}){return <>
 <section className="research-summary content-card"><span className="eyebrow">{r.company.status==='resolved'?'COMPANY IDENTIFIED':'IDENTITY NEEDS CLARIFICATION'}</span><h2>{r.company.name}</h2><p>{r.company.description}</p><p className="caption">{r.company.website} · Researched {new Date(r.createdAt).toLocaleString()}</p><p className="notice">{r.company.identityNote}</p><div className="button-group"><button className="button primary" disabled={!r.paths.length} onClick={()=>go(`play/${r.paths[0]?.playId}`)}><Compass size={16}/>Walk me through the map</button><button className="button secondary" onClick={()=>go('map')}>See highlighted map <ArrowRight size={16}/></button><button className="icon-button" aria-label="Export company research" onClick={()=>download(`SignalForce research ${r.company.name.replace(/[^a-zA-Z0-9 -]/g,'')}.json`,JSON.stringify(r,null,2),'application/json')}><Download size={18}/></button></div></section>
 <div className="section-heading"><h2>Conversations worth exploring</h2><span className="caption">Suggested order · not buying likelihood</span></div>
 {r.paths.length?r.paths.map((p,i)=><button className="research-path-card" key={p.playId} onClick={()=>go(`play/${p.playId}`)}><span className="research-number">{i+1}</span><span><strong>{playById[p.playId]?.title||p.playId}</strong><p>{p.hypothesis}</p><small>{p.evidenceIds.length} supporting finding{p.evidenceIds.length===1?'':'s'} · {personaById[p.personaId]?.short}</small></span><ArrowRight size={20}/></button>):<div className="notice">No supported pathway yet. {r.company.status==='resolved'?'More discovery is needed; absence of evidence is not evidence of no need.':'Try a more specific company name and official website.'}</div>}
 <details className="content-card research-detail" open><summary>Research coverage & gaps</summary><div className="coverage-grid">{r.coverage.map(c=><div key={c.area}><strong>{c.area}</strong><span className={`tag ${c.status==='found'?'green':'amber'}`}>{c.status}</span><p>{c.note}</p><Sources report={r} ids={c.sourceIds}/></div>)}</div>{r.gaps.map(g=><p className="research-gap" key={g}><TriangleAlert size={15}/>{g}</p>)}</details>
 <details className="content-card research-detail"><summary>All findings & sources ({r.findings.length})</summary>{r.findings.map(f=><article key={f.id} className="research-finding"><span className="tag blue">Reported evidence · {f.id}</span><h3>{f.title}</h3><p>{f.detail}</p><p className="caption">Published: {f.publishedDate||'not established'} · Period: {f.period||'not established'}</p><Sources report={r} ids={f.sourceIds}/><p className="notice">{f.limitation}</p></article>)}</details><p className="caption">{r.warnings.join(' ')}</p>
 </>}
export function CompanyLens({report,onClear,go}:{report:ResearchReport;onClear:()=>void;go:(r:string)=>void}){return <div className="company-lens"><Building2 size={19}/><div><strong>{report.company.name}</strong><span>Company lens · {report.paths.length} suggested paths · {new Date(report.createdAt).toLocaleDateString()}</span></div><button className="text-link" onClick={()=>go('research')}>Review evidence</button><button className="icon-button" aria-label="Remove company lens" onClick={onClear}><X size={16}/></button></div>}
export function CompanyPath({report,path,go,playing=false,onPlaying=()=>{}}:{report:ResearchReport;path:ResearchPath;go:(r:string)=>void;playing?:boolean;onPlaying?:(p:boolean)=>void}){
 const [step,setStep]=useState(0);useEffect(()=>{const n=Number(location.hash.split('/')[2]||0);setStep(Number.isInteger(n)&&n>=0&&n<8?n:0)},[report.id,path.playId,location.hash]);const play=playById[path.playId];const findings=report.findings.filter(f=>path.evidenceIds.includes(f.id));
 const steps=[{label:'Evidence',title:'What the sources actually say',text:''},{label:'Why now',title:'A reason to ask—not proof of urgency',text:path.whyNow},{label:'Problem',title:'The hypothesis to test',text:path.hypothesis},{label:'People',title:personaById[path.personaId].name,text:path.personaRationale},{label:'Approach',title:'What could help if the hypothesis holds',text:path.solutionFit},{label:'Products',title:'Capabilities to consider after discovery',text:path.productFit.replace(/\b[a-z]+(?:_[a-z0-9]+)+\b/g,id=>productById[id]?.canonicalName||id)+' Possible products: '+play.productIds.map(id=>productById[id].canonicalName).join(' · ')+'. '+play.prerequisites.join('. ')},{label:'Challenge',title:'What could make this wrong?',text:path.counter},{label:'Conversation',title:'Open with curiosity',text:path.opener}];
 const next=report.paths[report.paths.findIndex(p=>p.playId===path.playId)+1];
 const isDemo=report.id.startsWith('demo-');
 const duration=Math.max(11000,Math.min(26000,(steps[step].text.split(/\s+/).length+(step===0?90:step===7?90:step===3?65:0))*280+5000));
 useEffect(()=>{if(!playing||!isDemo)return;const timer=setTimeout(()=>{if(step<7)setStep(step+1);else if(next)go(`play/${next.playId}/0`);else{onPlaying(false);go('research')}},duration);return()=>clearTimeout(timer)},[playing,isDemo,step,path.playId,duration,next,go,onPlaying]);
 return <section className="company-path">{isDemo&&<div className="demo-controls"><span><Compass size={16}/><strong>Target demo</strong> · Saved research · No API usage</span><button className="button secondary" onClick={()=>onPlaying(!playing)}>{playing?<Pause size={15}/>:<Play size={15}/>} {playing?'Pause demo':'Resume demo'}</button><button className="text-link" onClick={()=>{onPlaying(false);go('map')}}>Explore the full map</button></div>}<div className="section-heading"><div><span className="eyebrow">{report.company.name} / GUIDED PATH</span><h2>From evidence to a useful question.</h2></div><span className="tag purple">{isDemo?'Teaching hypothesis · validate on the call':'AI-suggested · validate on the call'}</span></div><div className="research-step-tabs" role="group" aria-label="Company pathway walkthrough">{steps.map((s,i)=><button key={s.label} aria-pressed={step===i} className={step===i?'active':''} onClick={()=>setStep(i)}>{i+1}. {s.label}</button>)}</div><div key={step} className="research-step-body" aria-live="polite"><h3>{steps[step].title}</h3>{step===0?findings.map(f=><article key={f.id}><strong>{f.title}</strong><p>{f.detail}</p><Sources report={report} ids={f.sourceIds}/><small>{f.publishedDate||'Publication date not established'} · {f.limitation}</small></article>):<p>{steps[step].text}</p>}{step===2&&<ul>{path.painPoints.map(p=><li key={p}>{p}</li>)}</ul>}{step===3&&<div className="company-stakeholders">{path.partners.map(p=><article key={p.personaId}><strong>{personaById[p.personaId].name}</strong><p>{p.why}</p></article>)}</div>}{step===7&&<><ol>{path.questions.map(q=><li key={q}>{q}</li>)}</ol><h4>Qualify before recommending</h4><ul>{path.qualification.map(q=><li key={q}>{q}</li>)}</ul><p><strong>Small next step:</strong> {path.nextStep}</p></>}{step!==0&&<details><summary>Evidence behind this suggestion</summary>{findings.map(f=><article key={f.id}><p>{f.detail}</p><Sources report={report} ids={f.sourceIds}/></article>)}</details>}</div>{playing&&isDemo&&<div className="demo-timer" key={step+path.playId}><span style={{animationDuration:`${duration}ms`}}/></div>}<div className="section-heading"><button className="button secondary" disabled={!step} onClick={()=>setStep(step-1)}><ArrowLeft size={15}/>Back</button><span className="caption">{step+1} of {steps.length}</span>{step<7?<button className="button primary" onClick={()=>setStep(step+1)}>Next <ArrowRight size={16}/></button>:<button className="button primary" onClick={()=>go(next?`play/${next.playId}`:'research')}>{next?'Next suggested path':'Back to research'}<ArrowRight size={16}/></button>}</div></section>
}
